name: mesh_messenger_best_v1
description: Clean Best-of vertical slice for Mesh Messenger.
version: 0.1.4-best1-hil+5
publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_serial_communication: ^0.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
