name: service_studio
version: 0.9.0-alpha.8+26092508
publish_to: none
description: Universal service studio for ESP controllers, radio modules and Mesh Messenger hardware.
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/device_profiles.json
