[platformio]
default_envs = mmfw_dakerfpv_nano_c3_lr1121

[env:mmfw_dakerfpv_nano_c3_lr1121]
platform = espressif32@6.12.0
framework = arduino
board = esp32-c3-devkitm-1
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = min_spiffs.csv
lib_ldf_mode = deep+
lib_deps =
  jgromes/RadioLib@7.7.1
  bblanchon/ArduinoJson@7.4.3
build_flags =
  -D MM_FW_VERSION=\"0.4.4-dev\"
  -D MM_BOARD_DAKERFPV_NANO_C3=1
  -D MM_RADIO_LR1121=1
