#include "mm_uart.h"
#include <algorithm>
namespace mm::uart {
uint16_t crc16Ccitt(const uint8_t* data,size_t len,uint16_t initial){uint16_t crc=initial;for(size_t i=0;i<len;++i){crc^=static_cast<uint16_t>(data[i])<<8;for(int bit=0;bit<8;++bit)crc=(crc&0x8000)?static_cast<uint16_t>((crc<<1)^0x1021):static_cast<uint16_t>(crc<<1);}return crc;}
std::vector<uint8_t> cobsEncode(const uint8_t* data,size_t len){std::vector<uint8_t> out(len+len/254+2,0);size_t read=0,write=1,codeIndex=0;uint8_t code=1;while(read<len){if(data[read]==0){out[codeIndex]=code;code=1;codeIndex=write++;++read;}else{out[write++]=data[read++];++code;if(code==0xFF){out[codeIndex]=code;code=1;codeIndex=write++;}}}out[codeIndex]=code;out.resize(write);return out;}
bool cobsDecode(const uint8_t* data,size_t len,std::vector<uint8_t>& out,std::string& error){out.clear();out.reserve(len);size_t read=0;while(read<len){uint8_t code=data[read++];if(code==0){error="COBS_ZERO_CODE";return false;}size_t copyCount=static_cast<size_t>(code-1);if(read+copyCount>len){error="COBS_TRUNCATED";return false;}for(size_t i=0;i<copyCount;++i)out.push_back(data[read++]);if(code!=0xFF&&read<len)out.push_back(0);}return true;}
std::vector<uint8_t> encodeFrame(uint8_t type,uint16_t sequence,const uint8_t* payload,size_t payloadLen){if(payloadLen>0xFFFF)return{};std::vector<uint8_t> raw(6+payloadLen+2,0);raw[0]=VERSION;raw[1]=type;raw[2]=sequence&0xFF;raw[3]=sequence>>8;raw[4]=payloadLen&0xFF;raw[5]=payloadLen>>8;if(payloadLen)std::copy(payload,payload+payloadLen,raw.begin()+6);uint16_t crc=crc16Ccitt(raw.data(),raw.size()-2);raw[raw.size()-2]=crc&0xFF;raw[raw.size()-1]=crc>>8;auto framed=cobsEncode(raw.data(),raw.size());framed.push_back(0);return framed;}
bool decodeFrame(const uint8_t* encoded,size_t encodedLen,Frame& out,std::string& error){std::vector<uint8_t> raw;if(!cobsDecode(encoded,encodedLen,raw,error))return false;if(raw.size()<8){error="FRAME_TOO_SHORT";return false;}if(raw[0]!=VERSION){error="UNSUPPORTED_VERSION";return false;}uint16_t seq=raw[2]|(static_cast<uint16_t>(raw[3])<<8);uint16_t plen=raw[4]|(static_cast<uint16_t>(raw[5])<<8);if(raw.size()!=static_cast<size_t>(6+plen+2)){error="BAD_LENGTH";return false;}uint16_t expected=raw[raw.size()-2]|(static_cast<uint16_t>(raw[raw.size()-1])<<8);uint16_t actual=crc16Ccitt(raw.data(),raw.size()-2);if(expected!=actual){error="BAD_CRC";return false;}out.version=raw[0];out.type=raw[1];out.sequence=seq;out.payload.assign(raw.begin()+6,raw.begin()+6+plen);return true;}
}
