#include "emnext/io/project_io.hpp"
#include "emnext/io/result_io.hpp"
#include "emnext/io/sweep_io.hpp"
#include "emnext/io/optimizer_io.hpp"
#include "emnext/optimization/optimizer.hpp"
#include "emnext/core/model_tools.hpp"
#include "emnext/linalg/linear_solver.hpp"
#include "emnext/geometry/discretization.hpp"
#include "emnext/physics/dipole_reference.hpp"
#include "emnext/physics/wire_mom.hpp"
#include "emnext/physics/sweep.hpp"
#include "emnext/reference/nec2.hpp"

#include <chrono>
#include <cmath>
#include <filesystem>
#include <iomanip>
#include <iostream>
#include <numbers>
#include <string>
#include <vector>

namespace {
void usage(){std::cout<<"EMMana-Next bootstrap CLI\n"<<"Usage:\n"<<"  emnext inspect <project.emnx>\n"<<"  emnext model-check <project.emnx>\n"<<"  emnext mesh-info <project.emnx>\n"<<"  emnext export-nec <project.emnx> <output.nec>\n"<<"  emnext parse-nec <output.out>\n"<<"  emnext solve-exp <project.emnx>\n"<<"  emnext solve-exp-exact <project.emnx>\n"<<"  emnext solve-exp-span <project.emnx> <feed-span-m>\n"<<"  emnext solve-exp-json <project.emnx> <result.json>\n"<<"  emnext solve-exp-exact-json <project.emnx> <result.json>\n"<<"  emnext sweep-exp-json <project.emnx> <start-hz> <stop-hz> <points> <sweep.json> [reduced|exact]\n"<<"  emnext optimize-exp-json <project.emnx> <population> <generations> <seed> <optimizer.json> [reduced|exact] [de|pso|staged] [local-iterations] [w-match w-gain w-fb w-size gain-guardrail-db max-vswr band-start-hz band-stop-hz band-points quant-step-m tolerance-m robust-samples monte-carlo-samples]\n"<<"  emnext reference-dipole\n"<<"  emnext linalg-selftest\n"<<"  emnext linalg-benchmark <size> <repeats>\n";}
int inspect(const std::filesystem::path& path){const auto p=emnext::io::load_project(path);std::cout<<"Project: "<<p.name<<"\nSchema: "<<p.schema_version<<"\nFrequency: "<<std::fixed<<std::setprecision(3)<<p.frequency_hz/1e6<<" MHz\nWires: "<<p.wires.size()<<"\nFeeds: "<<p.feeds.size()<<"\n";return 0;}
int model_check(const std::filesystem::path& path){const auto p=emnext::io::load_project(path);const auto check=emnext::check_model(p);std::cout<<"Model hash: "<<emnext::stable_model_hash(p)<<"\n";for(const auto&w:check.warnings)std::cout<<"warning: "<<w<<"\n";for(const auto&e:check.errors)std::cout<<"error: "<<e<<"\n";std::cout<<(check.ok()?"MODEL OK":"MODEL INVALID")<<"\n";return check.ok()?0:2;}
int mesh_info(const std::filesystem::path& path){const auto p=emnext::io::load_project(path);const auto mesh=emnext::geometry::discretize(p);std::cout<<"Segments: "<<mesh.segments.size()<<"\n";for(const auto index:mesh.feed_segment_global_indices){const auto&s=mesh.segments.at(index);std::cout<<"Feed -> global "<<s.global_index<<", wire "<<s.wire_id<<", local "<<s.local_index<<", center=("<<s.center.x<<", "<<s.center.y<<", "<<s.center.z<<") m\n";}return 0;}
int export_nec(const std::filesystem::path& in,const std::filesystem::path& out){const auto p=emnext::io::load_project(in);const auto check=emnext::check_model(p);if(!check.ok()){std::cerr<<"Refusing NEC2 export: project model-check failed\n";return 2;}emnext::reference::write_nec2_deck(p,out);std::cout<<"NEC2 deck written: "<<out.string()<<"\n";return 0;}
int parse_nec(const std::filesystem::path& path){const auto result=emnext::reference::parse_nec2_output_file(path);if(result.frequency_hz)std::cout<<"Frequency: "<<std::fixed<<std::setprecision(6)<<*result.frequency_hz/1e6<<" MHz\n";if(result.feeds.empty()){std::cout<<"No NEC2 feed results found\n";return 2;}for(const auto&f:result.feeds)std::cout<<"Tag "<<f.tag<<" seg "<<f.segment<<" Z="<<std::setprecision(9)<<f.impedance_ohm.real()<<(f.impedance_ohm.imag()>=0.0?"+j":"-j")<<std::abs(f.impedance_ohm.imag())<<" ohm P="<<f.power_w<<" W\n";return 0;}
int solve_exp_with_source_span(const std::filesystem::path& path,double source_span_m,emnext::physics::WireKernelMode kernel_mode){auto p=emnext::io::load_project(path);if(source_span_m>0.0){if(p.feeds.empty())throw std::runtime_error("Project has no feed to override");p.feeds.front().source_span_m=source_span_m;}emnext::physics::WireMomSettings settings;settings.kernel_mode=kernel_mode;const auto result=emnext::physics::solve_wire_mom_experimental(p,settings);if(result.feeds.empty())return 2;const auto&f=result.feeds.front();std::cout<<"Solver: "<<result.solver_id<<" v"<<result.solver_version<<"\nSolver settings: "<<result.solver_settings_id<<"\nModel hash: "<<result.model_hash<<"\n"<<std::fixed<<std::setprecision(6)<<"Zin: "<<f.impedance_ohm.real()<<(f.impedance_ohm.imag()>=0.0?" + j":" - j")<<std::abs(f.impedance_ohm.imag())<<" ohm\nS11: "<<std::abs(f.s11)<<" (|Gamma|), VSWR: "<<f.vswr<<"\nAccepted power: "<<result.accepted_power_w<<" W\nRadiated power: "<<result.radiated_power_w<<" W\nDissipated power: "<<result.dissipated_power_w<<" W\nEfficiency: "<<result.efficiency<<"\nPower balance relative error: "<<result.power_balance_relative_error<<"\n";double dmax=0.0;for(const auto&ptn:result.pattern)dmax=std::max(dmax,ptn.directivity_linear);if(dmax>0.0)std::cout<<"Dmax: "<<dmax<<" ("<<10.0*std::log10(dmax)<<" dBi)\n";for(const auto&w:result.warnings)std::cout<<"warning: "<<w<<"\n";return 0;}
int solve_exp(const std::filesystem::path& path){return solve_exp_with_source_span(path,0.0,emnext::physics::WireKernelMode::Reduced);}int solve_exp_exact(const std::filesystem::path& path){return solve_exp_with_source_span(path,0.0,emnext::physics::WireKernelMode::CircumferentialExactStraight);}int solve_exp_span(const std::filesystem::path& path,double span_m){if(!(span_m>0.0))throw std::runtime_error("feed-span-m must be positive");return solve_exp_with_source_span(path,span_m,emnext::physics::WireKernelMode::Reduced);}
int solve_exp_json_with_kernel(const std::filesystem::path& input,const std::filesystem::path& output,emnext::physics::WireKernelMode kernel_mode){const auto p=emnext::io::load_project(input);emnext::physics::WireMomSettings settings;settings.kernel_mode=kernel_mode;const auto result=emnext::physics::solve_wire_mom_experimental(p,settings);emnext::io::write_result_json(result,output);std::cout<<"ResultSet written: "<<output.string()<<"\n";return 0;}
int solve_exp_json(const std::filesystem::path& input,const std::filesystem::path& output){return solve_exp_json_with_kernel(input,output,emnext::physics::WireKernelMode::Reduced);}int solve_exp_exact_json(const std::filesystem::path& input,const std::filesystem::path& output){return solve_exp_json_with_kernel(input,output,emnext::physics::WireKernelMode::CircumferentialExactStraight);}
int sweep_exp_json(const std::filesystem::path& input,double start_hz,double stop_hz,int points,const std::filesystem::path& output,const std::string& kernel){const auto p=emnext::io::load_project(input);emnext::physics::WireMomSettings settings;if(kernel=="reduced")settings.kernel_mode=emnext::physics::WireKernelMode::Reduced;else if(kernel=="exact")settings.kernel_mode=emnext::physics::WireKernelMode::CircumferentialExactStraight;else throw std::runtime_error("kernel must be reduced or exact");const auto sweep=emnext::physics::solve_frequency_sweep(p,start_hz,stop_hz,points,settings);emnext::io::write_sweep_json(sweep,output);std::cout<<"SweepResult written: "<<output.string()<<"\nSamples: "<<sweep.samples.size()<<"\nResonance marker: "<<std::fixed<<std::setprecision(6)<<sweep.resonance_frequency_hz/1e6<<" MHz\nMinimum S11: "<<sweep.min_s11_db<<" dB at "<<sweep.min_s11_frequency_hz/1e6<<" MHz\n";return 0;}
int optimize_exp_json(const std::filesystem::path& input,int population,int generations,std::uint64_t seed,const std::filesystem::path& output,const std::string& kernel,const std::string& algorithm,int local_iterations,double weight_match,double weight_gain,double weight_fb,double weight_size,double gain_guardrail_db,double max_vswr,double band_start_hz,double band_stop_hz,int band_points,double quantization_step_m,double manufacturing_tolerance_m,int robust_objective_samples,int monte_carlo_samples){const auto p=emnext::io::load_project(input);emnext::optimization::OptimizerSettings settings;settings.population=population;settings.generations=generations;settings.seed=seed;settings.algorithm=emnext::optimization::optimizer_algorithm_from_string(algorithm);settings.local_iterations=local_iterations;settings.weights={weight_match,weight_gain,weight_fb,weight_size};settings.gain_guardrail_db=gain_guardrail_db;settings.max_vswr=max_vswr;settings.band_start_hz=band_start_hz;settings.band_stop_hz=band_stop_hz;settings.band_points=band_points;settings.quantization_step_m=quantization_step_m;settings.manufacturing_tolerance_m=manufacturing_tolerance_m;settings.robust_objective_samples=robust_objective_samples;settings.monte_carlo_samples=monte_carlo_samples;if(kernel=="reduced")settings.kernel_mode=emnext::physics::WireKernelMode::Reduced;else if(kernel=="exact")settings.kernel_mode=emnext::physics::WireKernelMode::CircumferentialExactStraight;else throw std::runtime_error("kernel must be reduced or exact");const auto result=emnext::optimization::optimize_design(p,settings);emnext::io::write_optimizer_json(result,output);std::cout<<"OptimizerResult written: "<<output.string()<<"\nAlgorithm: "<<result.algorithm<<"\nInitial score: "<<result.initial.metrics.score<<"\nBest score: "<<result.best.metrics.score<<"\nFeasible: "<<(result.best.metrics.feasible?"yes":"no")<<"\nBand: "<<result.band_start_hz/1e6<<".."<<result.band_stop_hz/1e6<<" MHz / "<<result.band_points<<" points\nQuantization: "<<result.quantization_step_m*1e3<<" mm, tolerance: "<<result.manufacturing_tolerance_m*1e3<<" mm\nRobust objective samples: "<<result.robust_objective_samples<<", Monte Carlo: "<<result.monte_carlo_samples<<"\nEvaluations: "<<result.evaluations<<"\n";return 0;}
int reference_dipole(){using Ref=emnext::physics::HalfWaveDipoleReference;const double p=std::numbers::pi_v<double>;std::cout<<std::fixed<<std::setprecision(6)<<"Half-wave thin-dipole analytical reference\nDmax: "<<Ref::directivity_linear()<<" ("<<Ref::directivity_dbi()<<" dBi)\nZ at exact 0.5 lambda (reference, not resonant): "<<Ref::exact_halfwave_r_ohm()<<" + j"<<Ref::exact_halfwave_x_ohm()<<" ohm\nF(60 deg): "<<Ref::normalized_field(p/3.0)<<"\nF(90 deg): "<<Ref::normalized_field(p/2.0)<<"\nF(120 deg): "<<Ref::normalized_field(2.0*p/3.0)<<"\n";return 0;}
int linalg_selftest(){emnext::DenseMatrix a(2,2);a(0,0)={2.0,1.0};a(0,1)={1.0,-1.0};a(1,0)={3.0,0.0};a(1,1)={4.0,2.0};const std::vector<emnext::Complex> expected{{1.0,2.0},{-0.5,0.25}};std::vector<emnext::Complex>b(2);for(std::size_t r=0;r<2;++r)b[r]=a(r,0)*expected[0]+a(r,1)*expected[1];const auto solver=emnext::linalg::make_default_solver();const auto x=solver->solve(a,b);const double err=std::abs(x[0]-expected[0])+std::abs(x[1]-expected[1]);std::cout<<"Backend: "<<solver->name()<<"\nResidual check error: "<<std::setprecision(12)<<err<<"\n";return err<1e-10?0:2;}
int linalg_benchmark(int n,int repeats){if(n<2||n>2000)throw std::runtime_error("benchmark size must be in [2,2000]");if(repeats<1||repeats>100)throw std::runtime_error("benchmark repeats must be in [1,100]");emnext::DenseMatrix a(static_cast<std::size_t>(n),static_cast<std::size_t>(n));std::vector<emnext::Complex> expected(static_cast<std::size_t>(n));for(int i=0;i<n;++i){expected[static_cast<std::size_t>(i)]={1.0+0.001*static_cast<double>(i),-0.25+0.0005*static_cast<double>(i)};for(int j=0;j<n;++j){const double d=static_cast<double>(1+((i*17+j*31)%23));a(static_cast<std::size_t>(i),static_cast<std::size_t>(j))=i==j?emnext::Complex{static_cast<double>(n)+2.0+0.01*d,0.02*d}:emnext::Complex{0.002*d,-0.001*static_cast<double>((i+j)%11)};}}std::vector<emnext::Complex>b(static_cast<std::size_t>(n));for(int i=0;i<n;++i)for(int j=0;j<n;++j)b[static_cast<std::size_t>(i)]+=a(static_cast<std::size_t>(i),static_cast<std::size_t>(j))*expected[static_cast<std::size_t>(j)];const auto solver=emnext::linalg::make_default_solver();std::vector<emnext::Complex>x;const auto t0=std::chrono::steady_clock::now();for(int r=0;r<repeats;++r)x=solver->solve(a,b);const auto t1=std::chrono::steady_clock::now();const double total_ms=std::chrono::duration<double,std::milli>(t1-t0).count();const double residual=emnext::linalg::normalized_residual_inf(a,x,b);double solution_error=0.0;for(std::size_t i=0;i<x.size();++i)solution_error=std::max(solution_error,std::abs(x[i]-expected[i]));std::cout<<"Backend: "<<solver->name()<<"\nSize: "<<n<<"\nRepeats: "<<repeats<<"\nTotal ms: "<<std::fixed<<std::setprecision(3)<<total_ms<<"\nAverage ms: "<<total_ms/static_cast<double>(repeats)<<"\nNormalized residual: "<<std::scientific<<std::setprecision(12)<<residual<<"\nMax solution error: "<<solution_error<<"\n";return residual<1e-10&&solution_error<1e-9?0:2;}
}
int main(int argc,char**argv){try{if(argc<2){usage();return 1;}const std::string cmd=argv[1];if(cmd=="inspect"&&argc==3)return inspect(argv[2]);if(cmd=="model-check"&&argc==3)return model_check(argv[2]);if(cmd=="mesh-info"&&argc==3)return mesh_info(argv[2]);if(cmd=="export-nec"&&argc==4)return export_nec(argv[2],argv[3]);if(cmd=="parse-nec"&&argc==3)return parse_nec(argv[2]);if(cmd=="solve-exp"&&argc==3)return solve_exp(argv[2]);if(cmd=="solve-exp-exact"&&argc==3)return solve_exp_exact(argv[2]);if(cmd=="solve-exp-span"&&argc==4)return solve_exp_span(argv[2],std::stod(argv[3]));if(cmd=="solve-exp-json"&&argc==4)return solve_exp_json(argv[2],argv[3]);if(cmd=="solve-exp-exact-json"&&argc==4)return solve_exp_exact_json(argv[2],argv[3]);if(cmd=="sweep-exp-json"&&(argc==7||argc==8))return sweep_exp_json(argv[2],std::stod(argv[3]),std::stod(argv[4]),std::stoi(argv[5]),argv[6],argc==8?argv[7]:"reduced");if(cmd=="optimize-exp-json"&&argc>=7&&argc<=23)return optimize_exp_json(argv[2],std::stoi(argv[3]),std::stoi(argv[4]),static_cast<std::uint64_t>(std::stoull(argv[5])),argv[6],argc>=8?argv[7]:"reduced",argc>=9?argv[8]:"staged",argc>=10?std::stoi(argv[9]):12,argc>=11?std::stod(argv[10]):0.40,argc>=12?std::stod(argv[11]):0.30,argc>=13?std::stod(argv[12]):0.20,argc>=14?std::stod(argv[13]):0.10,argc>=15?std::stod(argv[14]):0.50,argc>=16?std::stod(argv[15]):2.0,argc>=17?std::stod(argv[16]):0.0,argc>=18?std::stod(argv[17]):0.0,argc>=19?std::stoi(argv[18]):1,argc>=20?std::stod(argv[19]):0.0,argc>=21?std::stod(argv[20]):0.0,argc>=22?std::stoi(argv[21]):0,argc>=23?std::stoi(argv[22]):0);if(cmd=="reference-dipole")return reference_dipole();if(cmd=="linalg-selftest")return linalg_selftest();if(cmd=="linalg-benchmark"&&argc==4)return linalg_benchmark(std::stoi(argv[2]),std::stoi(argv[3]));usage();return 1;}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<"\n";return 2;}}
